// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export let environment = {
  name: 'uat',
  production: false,
  version: env.npm_package_version,
  serverUrl: 'https://paymenthub.uat.oneacrefund.org/opsapp',
  oauth: {
    enabled: true,  // For connecting to Mifos X using OAuth2 Authentication change the value to true
    serverUrl: (window as any)?.env?.authServerUrl || 'https://accounts.uat.oneacrefund.org',
    realm: (window as any)?.env?.keycloakRealm || 'OneAcreFund',
    client_id: (window as any)?.env?.keycloakClientId || 'paymenthub',
    tokenUrl: `https://accounts.uat.oneacrefund.org/auth/realms/OneAcreFund/protocol/openid-connect/token`,
    redirectUri: (window as any)?.env?.redirectUri || 'https://ph-web.uat.oneacrefund.org/home'
  },
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  externalConfigurationFile: '',
  auth: {
    enabled: false,
    tenant: 'oaf',
  },
  amsShortCodes: [
    {
      option: 'ERPLY_TILL',
      type: 'TILL',
      value: '9499081',
    },
    {
      option: 'TUPANDE_TILL',
      type: 'TILL',
      value: '6064956',
    },
    {
      option: 'PAYGOPS_USSD_KE_TILL',
      type: 'TILL',
      value: '9347335',
    },
    {
      option: 'ROSTER_USSD_KE_TILL',
      type: 'TILL',
      value: '9558723',
    },
    {
      option: 'ODOO_KE_TILL',
      type: 'TILL',
      value: '9491775',
    },
    {
      option: 'FINERACT_USSD_KE_TILL',
      type: 'TILL',
      value: '8167094',
    },
    {
      option: 'FINERACT_KE_PAYBILL',
      type: 'PAYBILL',
      value: '840706',
    },
    {
      option: 'TEST_PAYBILL',
      type: 'PAYBILL',
      value: '840700',
    },
  ],
  matomo: {
    url: 'https://analytics.oneacrefund.org',
    siteId: 18, // Replace with your production site ID
    disabled: false,
  },
};
